USEPA/haztrak

client/src/components/ManifestForm/HandlerForm/HandlerForm.tsx, client/src/components/ManifestForm/ManifestForm/ManifestForm.tsx, client/src/components/ManifestForm/Transporter/TransporterSearch.tsx, client/src/components/ManifestForm/Transporter/TransporterSearchForm.tsx, client/src/components/ManifestForm/Transporter/TransporterTable.tsx, client/src/types/Manifest/Manifest.ts, client/src/types/Transporter/Transporter.ts
Transporters added to the object created with the manifest form is a Transporter type, not Handler. When a transporter is added via the TransporterSearchForm, a new transporter is created by adding  `order` to the existing `Handler` object and appending to the array of tranporters. 
closes #188
=> Fix: convert Handler to new Transporter type on manifest

client/src/components/ManifestForm/ManifestForm/ManifestForm.tsx, client/src/components/ManifestForm/Transporter/TransporterRowActions.tsx, client/src/components/ManifestForm/Transporter/TransporterSearch.tsx, client/src/components/ManifestForm/Transporter/TransporterSearchForm.tsx, client/src/components/ManifestForm/Transporter/TransporterTable.tsx, client/src/components/ManifestForm/Transporter/TransporterTable/TransporterRowActions.tsx, client/src/components/ManifestForm/Transporter/TransporterTable/TransporterTable.tsx, client/src/components/ManifestForm/Transporter/TransporterTable/index.ts, client/src/components/ManifestForm/Transporter/index.ts
This PR adds the ability to remove transporters from the manifest, the manifest automatically modifies the order field of each transporter when a transporter from the array is removed (a row is deleted).  
I don't have time for to write up a test, but I believe a couple tests for this component would be worth the effort. 
closes #194
=> 194 transporter remove action

client/src/App.tsx, client/src/components/HtCard/HtCard.tsx, client/src/components/HtError/HtError.tsx, client/src/components/HtError/index.ts, client/src/components/HtSpinner/HtSpinner.tsx, client/src/components/HtSpinner/index.ts, client/src/features/manifest/ManifestDetails/ManifestDetails.tsx
This PR adds an HtError component, all unknown routes are sent to it. Also explored using react-error-boundary but did not like the need to reset the error state via all methods to navigate from the error page. May look again at this again in the future.
=> add HtSpinner, refactor out of HtCard, initial HtError

client/src/components/ManifestForm/ManifestForm.tsx, client/src/components/ManifestForm/Transporter/TransporterTable/TransporterTable.tsx, client/src/components/ManifestForm/WasteLine/WasteLineTable/WasteLineTable.tsx, client/src/components/ManifestForm/WasteLine/WasteLineTable/index.ts
This PR adds a rudimentary display to shows WasteLine objects attached to a given manifest. It should be reusable for viewing and editing manifest waste lines.
closes #217
=> initial waste line table display

client/src/components/ManifestForm/ManifestForm.tsx, client/src/components/ManifestForm/Transporter/TransporterTable/TransporterRowActions.spec.tsx, client/src/components/ManifestForm/Transporter/TransporterTable/TransporterRowActions.tsx, client/src/components/ManifestForm/Transporter/TransporterTable/TransporterTable.spec.tsx, client/src/components/ManifestForm/Transporter/TransporterTable/TransporterTable.tsx, client/src/types/Manifest/Contact.ts, docker-compose.dev.yaml, server/apps/trak/views/handler.py, server/apps/trak/views/manifest.py, server/apps/trak/views/sites.py
This PR adds the ability to re-order the transporters listed on a draft manifest, as well as tests and some cosmetic aspects of the transporter re-order actions. 
The first row (transporter 1) has its "move up" (move towards the front of the list) button disabled and vice versa for the last transporters and the move down button. 
closes #202
=> 202 transporter row action swap order

client/src/components/Notification/Notification.tsx
This commit hides the notification badge when the number of alerts is equal to zero
closes #255 
Below are screenshots to verify my solution
=> removes notification badge when no. of alerts is 0

.github/workflows/gh_pages.yaml, docker-compose.yaml, server/fixtures/dev_data.json
This is a small PR that adds a limited set of fixtures (discussed [here](https://github.com/USEPA/haztrak/issues/281#issuecomment-1374189178)) so developers have  data in the local development environment to work against.
It also has 2 minor fixes
* A healthcheck for the postgres service so the django/celery services don't try to connect to the postgres db too early<sup>1</sup>
* fix gh_pages trigger condition to follow the actions start-workflow examples.
<sup>1</sup> The django/celery services sometimes failed, because while the postgres container had been started, the postgres db was not ready to accept connections. This often happened when it was the first time running `docker-compose up`.
=> 281 add dev fixtures

.github/release-drafter.yml, .github/workflows/release-drafter.yaml, .github/workflows/release.yaml
This PR adds the [draft-releaser]() marketplace action to our CI/CD pipeline. I'm not sure if this will work since there's no good way to test this without running it with the necessary config files in the GH default branch. 
relevant to #398
=> Add release-drafter  to CI/CD pipeline

client/package.json, client/src/components/HandlerDetails/HandlerDetails.tsx, client/src/components/ManifestForm/ManifestForm.tsx, client/src/components/ManifestForm/Transporter/TransporterTable/TransporterTable.tsx, client/src/features/manifest/ManifestDetails.tsx, client/src/types/Handler/handler.ts, server/apps/trak/models/address_model.py, server/apps/trak/models/base_model.py, server/apps/trak/models/contact_model.py, server/apps/trak/models/handler_model.py, server/apps/trak/models/manifest_model.py, server/apps/trak/models/rcra_profile_model.py, server/apps/trak/models/signature_model.py, server/apps/trak/models/site_model.py, server/apps/trak/models/site_permission_model.py, server/apps/trak/models/transporter_model.py, server/apps/trak/models/waste_model.py, server/apps/trak/serializers/address_ser.py, server/apps/trak/serializers/handler_ser.py, server/apps/trak/serializers/manifest_ser.py, server/apps/trak/serializers/transporter_ser.py, server/apps/trak/services/site_service.py, server/apps/trak/tests/conftest.py, server/apps/trak/tests/models/test_handler.py, server/pyproject.toml
This PR adds the ability to see whether a handler on a manifest has signed. 
- `signed` property added to ManifestHandler model and corresponding serializers (`ManifestHandlerSerializer` and `TransporterSerializer`)
- `signed: string` type added to `ManifestHandler` interface on front end
- use new `signed` property to indicate whether a handler (generator, transporter, tsdf) has signed a manifests
I created a new `TrakBaseModel` abstract base class for all apps.trak.models classes. This offers us a uniform __repr__ implementation. 
close #377
=> 377 manifest handler `signed` indicator

README.md, client/src/components/HandlerDetails/HandlerDetails.spec.tsx, client/src/components/HandlerDetails/HandlerDetails.tsx, client/src/components/Ht/HtForm.tsx, client/src/components/Ht/HtPaginate/HtPaginate.spec.tsx, client/src/components/ManifestForm/ManifestForm.tsx, client/src/components/ManifestForm/Transporter/TransporterTable/TransporterTable.tsx, client/src/components/QuickerSign/QuickerSign.spec.tsx, client/src/components/QuickerSign/QuickerSign.tsx, client/src/components/QuickerSign/QuickerSignForm.tsx, client/src/components/QuickerSign/QuickerSignModal.tsx, client/src/components/QuickerSign/QuickerSignModalBtn.tsx, client/src/components/QuickerSign/index.ts, client/src/components/buttons/RcraApiUserBtn/RcraApiUserBtn.tsx, client/src/components/buttons/SyncManifestBtn/SyncManifestBtn.tsx, client/src/features/manifest/MtnList.tsx, client/src/features/profile/RcraProfile/RcraProfile.tsx, client/src/test-utils/fixtures/index.ts, client/src/test-utils/fixtures/mockHandler.ts, client/src/test-utils/fixtures/mockManifest.ts, client/src/types/handler/handler.ts, client/src/types/manifest/signatures.ts, server/apps/trak/models/handler_model.py
This PR adds the ability to submit electronic (Quicker Sign) signatures from the (react) client. This also adjust the gating for the `SyncManifestBtn`, `RcraApiUserBtn` and the new `QuickerSignModalBtn`. The Quicker Sign Form has default values of the user's username and the current date. (however, we may consider remove the default username since we want the signature to be an intention action. 
We also need to add front end validation for the QuickerSignForm. 
The following general rules apply for the above buttons
1. for `SyncManifestBtn` there must be a siteId to sync to
2. for `RcraApiUserBtn` the user's profile must have `apiUser` set to true in the redux store (in thier RcraProfile)
3. for `QuickerSignModalBtn` the manifest must be in either
- `"Scheduled"`
- `"InTransit" `
- …
=> Quicker sign submit

client/src/components/Ht/HtTooltip/HtTooltip.tsx, client/src/components/Ht/HtTooltip/index.ts, client/src/components/ManifestForm/ManifestForm.spec.tsx, client/src/components/ManifestForm/ManifestForm.tsx, client/src/components/ManifestForm/manifestSchema.ts, server/apps/sites/views/site_views.py
Adds Manifest Schema validation logic for the manifest potential ship date. This is not the highest priority field but was an easy one to go thru the motions on to get the hang of using the [zod library](https://zod.dev/). A new test in the ManifestForm test suite is included.  
This PR also includes a fix to the handler search endpoint (RcraSiteSearchView), and also adds a InfoIconTooltip component for quickly adding a small info circle icon that will dispaly a help message when hovered over.
Does not directly closes a ticket
related to #106
=> Potential ship date validation

client/src/components/ManifestForm/ManifestForm.spec.tsx, client/src/components/ManifestForm/ManifestForm.tsx, client/src/components/ManifestForm/manifestSchema.ts, client/src/test-utils/fixtures/mockManifest.ts
This PR fixes a bug where dates managed by RCRAInfo/e-Manifest, such as `createdDate`, `updatedDate`, and `shippedDate` where not being displayed in the manifest form. A regression test is added. 
relevant to #106 but closes no tickets.
=> Rcra date field bugs

client/src/components/ManifestForm/ManifestForm.tsx, client/src/components/ManifestForm/manifestSchema.ts, docker-compose.yaml
This PR adds some logic to the ManifestForm as to whether the fields can be edited. Now, once the manifest has reached a `Scheduled` status neither of the fields can be edited. It also adds the rest of the remaining options to both of these select fields (as hidden choices which we use to display the current status and submission type but do not allow them to be edited once they reach the point in the shipment life cycle that they are managed by the EPA RCRAInfo system).
This PR also re-adds a named volume back to the docker compose file.
This PR also adds initial default values for the `ManifestForm`
relevant to #443 
closes #439
=> ManifestForm status validation/logic and SubmissionType logic

.github/pull_request_template.md, client/src/components/ErrorBoundary/ErrorBoundary.tsx
This PR adds a button to the `ErrorBoundary` component that resets the `hasError` state. It does not navigate back as described in #342 
closes #342
=> Reset error state

.idea/runConfigurations/Test_All.xml, client/src/components/Manifest/Address/AddressForm.tsx, client/src/components/Manifest/Contact/ContactForm.spec.tsx, client/src/components/Manifest/Contact/ContactForm.tsx, client/src/components/Manifest/Contact/PhoneForm.spec.tsx, client/src/components/Manifest/Contact/PhoneForm.tsx, client/src/components/Manifest/Contact/index.ts, client/src/components/Manifest/Handler/HandlerForm.tsx, client/src/components/Manifest/ManifestForm.tsx, client/src/components/Manifest/index.ts, client/src/components/RcraSite/rcraSiteSchema.ts, client/src/test-utils/render.tsx, docs/haztrak_book/src/development/contributing.md
This PR creates a new `PhoneForm` in the context of the manifest. It is used to gather user input on a handler's `emergencyPhone` field (is separate from the `contact` object) It is rendered by the `ContactForm` in a a `HandlerForm`. Keeping it as a separate component means we can use it outside the contact form (which we will need to do later) in instances where the handler details are read only but they still need to provide the emergency phone number on a per-manifest basis.
This PR also makes some small non-functional UI adjustments to the Handler form inputs, namely adjusting the width to more closely align with the length of the expected input, and using bootstrap styling in our react-select components.
=> Emergency phone field

client/src/App.scss, client/src/components/Ht/HtCard/HtCard.tsx, client/src/components/Ht/HtPaginate/HtPageBtns.tsx, client/src/components/Ht/HtPaginate/HtPageControls.tsx, client/src/components/Ht/HtPaginate/index.ts, client/src/components/Ht/index.ts, client/src/components/Mtn/MtnTable.spec.tsx, client/src/components/Mtn/MtnTable.tsx, client/src/features/manifest/Manifest.tsx, client/src/features/manifest/NewManifest.tsx, client/src/hooks/usePagination/usePagination.spec.tsx, client/src/hooks/usePagination/usePagination.tsx, client/src/store/rcraProfileSlice/rcraProfileSlice.spec.tsx
This PR adds the functionality necessary to filter the manifest table by the manifest's current status (users can already filter by MTN). 
In addition, it also updates the pagination component to give it a fresh look and ensure that ellipsis are displayed correctly 
for example, the three scenarios below...
ellipsis right of active page
ellipsis left of active page
ellipsis on both sides of active page
This PR udpates the inline comments in the `usePagination` custom hook to be a little more helpful.
tests are included. 
closes #401
=> Filter by status

client/src/components/Mtn/MtnTable.spec.tsx, client/src/components/Mtn/MtnTable.tsx
This PR adds the ability to sort the MtnTable component (Manifest table) alphanumerically by the existing columns. We do not serialize the last update date on the server (like mentioned in #415), however, this sets up the infrastructure for sorting by a column.
relevant to #415
=> Mtn table sorting

client/src/components/AdditionalInfo/additionalInfoSchema.ts, client/src/components/Manifest/ManifestForm.tsx, client/src/components/Manifest/manifestSchema.ts
This small PR adds validation to our front end for draft manifests that requires user to supply at least 1 transporter. 
simple as that. 
closes #468
=> Transporter required validation

client/src/App.tsx, client/src/components/Manifest/QuickerSign/QuickerSignForm.tsx, client/src/components/Manifest/SiteSelect/SiteSelect.tsx, client/src/components/Notification/NotificationBtn.tsx, client/src/components/buttons/RcraApiUserBtn/RcraApiUserBtn.tsx, client/src/features/home/Home.tsx, client/src/features/login/Login.tsx, client/src/features/manifest/NewManifest.tsx, client/src/features/notifications/Notifications.tsx, client/src/features/profile/Profile.tsx, client/src/store/notificationSlice/index.ts, client/src/store/notificationSlice/notification.slice.ts, client/src/store/rcraProfileSlice/index.ts, client/src/store/rcraProfileSlice/rcraProfile.slice.ts, client/src/store/rcraProfileSlice/rcraProfileSlice.spec.tsx, client/src/store/userSlice/index.ts, client/src/store/userSlice/user.slice.ts, docs/haztrak_book/src/design/browser-client.md, docs/haztrak_book/src/design/source-roadmap.md, server/apps/trak/models/manifest_models.py
This PR introduces real selectors into our project (something that should have been done a LONG time ago) so our redux state is encapsulated and the details remain hidden/abstracted from our components. This way we can change the structure of our redux state without having to change all our components that rely on that state.  
closes #470
=> remove ad hoc selectors

client/src/App.scss, client/src/components/Nav/TopNav.tsx, runhaz.sh
This PR modifies our sidebar navigation toggle button by moving it to a location that a user would  expect it to be at instead of floating around in the middle of the top navigation bar. It takes inspiration from the google cloud console (also, it just didn't really make an sesne where it was before).
closes #516
=> 516 navigation icon location

.github/dependabot.yml, client/src/App.scss, client/src/components/Nav/TopNav.tsx, client/src/components/Notification/NotificationBtn.tsx
This is a quick fix for the notification icon that disappeared when there were not notifications. 
closes #515
=> remove text-muted from notification icon

client/src/components/Manifest/WasteLine/QuantityForm.tsx, client/src/components/Manifest/WasteLine/WasteLineForm.tsx, client/src/components/Manifest/WasteLine/WasteLineTable/WasteLineTable.tsx, client/src/components/Manifest/WasteLine/wasteLineSchema.ts, client/src/components/Manifest/manifestSchema.ts, client/src/components/Notification/NotificationBtn.tsx, client/src/features/profile/RcraProfile.tsx, client/src/test-utils/fixtures/mockWaste.ts
This PR replaces the typescript interface with the zod object schema for the wasteline. The `wasteLineSchema` object can be used for validation and as a type interface. 
We also make some small cosmetic changes to the `WasteLineTable` component.
closes #184
=> Waste line schema and cosmetics

.github/release-drafter.yml, .github/workflows/test_client.yaml, .idea/runConfigurations/Client.xml, .idea/runConfigurations/Vitest_Run.xml, .idea/runConfigurations/Vitest_Watch.xml, client/src/components/Manifest/ManifestForm.spec.tsx, client/src/components/Manifest/ManifestForm.tsx, client/src/components/Manifest/manifestSchema.ts, client/src/features/home/Home.spec.tsx, client/src/features/home/Home.tsx, client/src/store/rcraProfileSlice/rcraProfile.slice.ts, client/src/test-utils/mock/handlers.ts
This PR updates our manifest schema level validation so that users must supply at least 1 waste line before they can save a new manifest. 
The PR includes an error message (in the form of an alert) if at least 1 waste line is not provided 
outside of that, I've updated the .idea run configs to use the environment variables (specifically for mocking API calls). 
closes #467
=> manifest must have wasteline

client/src/components/Manifest/ManifestForm.spec.tsx, client/src/components/Manifest/ManifestForm.tsx, client/src/components/Manifest/manifestSchema.ts
This PR adds the validation (through the zod library) to check that a manifest has a valid tsdf provided before it can be successfully saved. Similar to what we added for the generator, transporter, and waste lines earlier today in #466. 
closes #469
=> manifest must have tsdf

.github/workflows/test_server.yaml, client/src/components/Manifest/Address/AddressForm.tsx, client/src/components/Manifest/ManifestForm.tsx, client/src/components/Manifest/manifestSchema.ts, configs/.env.test, runhaz.sh, server/haztrak/settings.py
This PR does what #538 was supposed to do. embarrassing but it's ok. no downtime.
=> Revert to 534

client/src/components/Manifest/ManifestForm.tsx
This PR fixes the bug where the status field becomes disabled after a draft manifest is set to scheduled.
closes #478
=> fix draft manifest disabled status

server/apps/core/views/profile_views.py, server/apps/core/views/task_views.py, server/apps/trak/views/manifest_view.py, server/haztrak/settings.py, server/haztrak/urls.py
This is a quick chore/fix that allows haztrak developers to use the browsable API as described in the DRF docs here https://www.django-rest-framework.org/tutorial/4-authentication-and-permissions/#adding-login-to-the-browsable-api.
It's embarrassing I haven't had this setup a long time LOL. Very convenient.
=> Browsable api auth

client/src/components/Manifest/WasteLine/HazardousWasteForm/HazardousWasteForm.tsx, client/src/components/Manifest/WasteLine/WasteLineForm.tsx, client/src/components/Manifest/WasteLine/WasteLineTable/WasteRowActions.tsx, client/src/components/Manifest/WasteLine/wasteLineSchema.ts
Quick PR that adds validation which requires at least one federal waste code is required if `epaWaste` is true.
=> Federal waste codes required if epaWaste is true

client/package-lock.json, client/package.json, client/src/components/Manifest/ManifestForm.tsx, client/src/components/Manifest/QuickerSign/QuickerSignForm.tsx, client/src/components/buttons/SyncManifestBtn/SyncManifestBtn.spec.tsx, client/src/components/buttons/SyncManifestBtn/SyncManifestBtn.tsx, client/src/features/home/Home.spec.tsx, client/src/features/manifestDetails/ManifestDetails.tsx, client/src/features/manifestList/ManifestList.tsx, client/src/features/notifications/Notifications.tsx, client/src/features/profile/RcraProfile.tsx, client/src/store/rcraProfileSlice/rcraProfile.slice.ts, client/src/store/site.slice.ts, client/src/store/wasteCode.slice.ts, client/src/test-utils/mock/handlers.ts, server/apps/core/urls.py, server/apps/sites/tests/test_epa_profile_views.py, server/apps/sites/tests/test_epa_site_views.py, server/apps/sites/tests/test_site_views.py, server/apps/sites/urls.py, server/apps/sites/views/__init__.py, server/apps/sites/views/site_views.py, server/apps/trak/tests/views/test_manifest_views.py, server/apps/trak/urls.py, server/apps/trak/views/__init__.py, server/apps/trak/views/manifest_view.py, server/haztrak/settings.py
Removes a (surprising amount) of unused handler functions (django calls them views) from our rest API design. we also add the 'rcra' accronym (for Resource Conservation and Recovery) into our RESTful API url pattern to roughly signify that a resource is 
1. related to RCRA and not another EPA AA-ship like the clean water or clean air acts (there could be a `site` or `epaId` resource in those acts, although I'm not sure). This clarifies and makes the app a little more extensible if that information was added at a later date. 
2. the resource (again roughly) should follow the schemas described in the USEAP/e-manifest documentation.  
We also update the auto generated OpenAPI page to better reflect the organization of resources, and add useful details about the requests/responses of our API …
=> Rest api design

.github/workflows/build_image.yaml
adds arguments for building our images for architectures `linux/amd64` and `linux/arm64`
=> add platform args to build_image workflow

infra/gcp/dev/.terraform.lock.hcl, infra/gcp/dev/README.md, infra/gcp/dev/backend.tf, infra/gcp/dev/main.tf, infra/gcp/dev/variables.tf, infra/gcp/modules/gcp-apis/variables.tf, infra/gcp/modules/k8/main.tf, infra/gcp/modules/k8/outputs.tf, infra/gcp/modules/k8/variables.tf, infra/gcp/modules/network/main.tf, infra/gcp/modules/network/outputs.tf, infra/gcp/modules/network/variables.tf
This PR adds a local module that wraps around google's [kubernetes-engine](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine) module. 
It employs the module in our GCP/dev example configs. The reference implementation deploys a simple, zonal public cluster which we'll build on for creating an example k8 deployment for haztrak.
=> GKE terraform module

.github/workflows/terraform_lint.yaml
Adds a workflow that check terraform configuration are properly formatted and can be validated through the terraform CLI.
=> Terraform linting CI workflow

.github/workflows/test_server.yaml, docker-compose.yaml, server/haztrak/settings/base.py, server/haztrak/urls.py, server/requirements.txt
This PR makes 2 modifications. 
1. Adds a new dependency `django-health-check` to implement a health check endpoint. 
2. Updates our Postgres version from 14, past 15, to 16. This is done in our docker compose, and github actions workflow (we'll see if the CI runs).
=> Health checks and POSTGRES 16

docs/guide/src/development/local-development.md
Adds a short blurb for newcomers to get up and running on their local machine about how the app is exposed on their local machine.
=> add docs on exposed ports for local developement

.github/workflows/test_server.yaml, server/Dockerfile, server/requirements.txt, server/requirements_dev.txt
since Celery 5.3.5 supports python 3.12 we can safely migrate the codebase to python 3.12. Yippee!
=> Python 3.12 migration

client/src/components/HaztrakSite/SiteTable.tsx, client/src/components/HaztrakSite/SiteTableRowActions.tsx, client/src/components/Manifest/Transporter/TransporterRowActions.tsx, client/src/components/Mtn/MtnTable.tsx, client/src/components/buttons/SyncManifestBtn/SyncManifestBtn.tsx, client/src/features/SiteList/SiteList.tsx, client/src/features/manifestList/ManifestList.tsx, client/src/hooks/useProgressTracker/useProgressTracker.tsx, client/src/store/haztrakApiSlice.ts, client/src/store/index.ts, server/apps/sites/services/site_services.py
Uses our new custom hook (that I'm very happy with and proud of LOL) to track long-running task progress while syncing a site's manifests. in addition, we pass state of the sync progress to the sync manifest button, allowing us to poll the server while the task is running and display newly added manifest as they are added. Also some UI candy like spinning the site sync icon.
=> UseProgressTracker hook during manifest sync

client/.dockerignore, client/src/components/Manifest/Actions/ManifestFABs.tsx, client/src/components/Manifest/GeneralInfo/GeneralInfoForm.spec.tsx, client/src/components/Manifest/GeneralInfo/GeneralInfoForm.tsx, client/src/components/Manifest/GeneralInfo/ManifestStatusField.spec.tsx, client/src/components/Manifest/GeneralInfo/ManifestStatusField.tsx, client/src/components/Manifest/ManifestForm.spec.tsx, client/src/components/Manifest/ManifestForm.tsx, client/src/components/Manifest/QuickerSign/SignBtn/QuickSignBtn.spec.tsx, client/src/components/Manifest/Transporter/TransporterTable.spec.tsx, client/src/components/Manifest/WasteLine/DotIdSelect.tsx, client/src/components/Manifest/WasteLine/WasteLineForm.spec.tsx, client/src/components/Manifest/manifestSchema.ts, client/src/features/NewManifest/NewManifest.tsx, client/src/features/SiteDetails/SiteDetails.tsx, client/src/hooks/manifest/index.ts, client/src/hooks/manifest/useManifestStatus/useManifestStatus.spec.tsx, client/src/hooks/manifest/useManifestStatus/useManifestStatus.tsx, client/src/services/manifest/manifest.spec.ts, client/src/services/manifest/manifest.ts, client/src/store/manifestSlice/manifest.slice.spec.tsx, client/src/store/manifestSlice/manifest.slice.ts, client/src/store/rootStore.ts, client/src/test-utils/fixtures/mockWaste.ts, client/src/test-utils/mock/index.ts, client/src/test-utils/mock/wasteApiMocks.ts, client/src/test-utils/render.tsx
This PR adjust the criteria for when the `Scheduled` option is available on the manifest form. It is displayed as disabled if ther user does not have access to the TSDF listed on the manifest (or no TSDF is added). 
In addition, we've converted the manifest type to a react-select component for consistent style. 
closes #565
=> Scheduled status disabling

client/src/components/Manifest/GeneralInfo/GeneralInfoForm.tsx, client/src/components/Manifest/GeneralInfo/ManifestStatusSelect.spec.tsx, client/src/components/Manifest/GeneralInfo/ManifestStatusSelect.tsx, client/src/components/Manifest/GeneralInfo/ManifestTypeField.spec.tsx, client/src/components/Manifest/GeneralInfo/ManifestTypeSelect.tsx
This PR adjust the manifest type select input. The new component
1. has `Hybrid` type as the default
2. `FullElectronic` option is disabled if a generator has not been added to the manifest
3. `FullElectronic` option is disabled if the selected generator cannot e-Sign
4. has unit tests associated with the component. 
closes #673
=> Manifest type option availability

.idea/runConfigurations/Vitest_Coverage.xml, .idea/runConfigurations/Vitest_UI.xml, client/package-lock.json, client/package.json, client/src/components/Manifest/GeneralInfo/GeneralInfoForm.tsx, client/src/components/Manifest/GeneralInfo/ManifestStatusSelect.spec.tsx, client/src/components/Manifest/GeneralInfo/ManifestStatusSelect.tsx, client/src/components/Manifest/GeneralInfo/ManifestTypeField.spec.tsx, client/src/components/Manifest/GeneralInfo/ManifestTypeSelect.tsx, client/src/components/Manifest/Transporter/TransporterRowActions.tsx, client/src/components/Manifest/Transporter/TransporterTable.tsx, client/src/components/Manifest/WasteLine/QuantityForm.spec.tsx, client/src/components/Manifest/WasteLine/QuantityForm.tsx, client/src/components/Manifest/WasteLine/WasteLineForm.tsx, client/src/components/Manifest/WasteLine/WasteLineTable/WasteLineTable.tsx, client/src/components/Manifest/WasteLine/WasteLineTable/WasteRowActions.tsx, client/src/components/Manifest/WasteLine/wasteLineSchema.ts, client/vite.config.ts
This PR updates the UI for our waste lines on a manifest. It converts the display from a table to list of collapsible cards/Accordions. We're not worried about too many waste lines as most manifest have a limited number of waste lines to begin with. The new waste line UI reflects the transporters. 
closes #622
=> Wasteline table UI updates

client/src/store/userSlice/user.slice.ts
Quick fix URL used for login endpoint on our front end. 
For reference, since we reorged the django apps, we now have all user endpoints under the `user` resource. 
so `/api/login` became `/api/user/login`
=> Auth URL fix

client/src/components/RcraProfile/RcraProfile.tsx, client/src/store/htApi.slice.ts, server/apps/conftest.py, server/apps/core/admin.py, server/apps/core/services/rcrainfo_service.py, server/apps/handler/admin.py, server/apps/manifest/services/emanifest.py, server/apps/manifest/services/emanifest_search.py, server/apps/manifest/tasks.py, server/apps/manifest/tests/test_search_emanifest.py, server/apps/org/admin.py, server/apps/profile/serializers/rcrasite_access.py, server/apps/site/services.py, server/haztrak/urls.py
This PR adds a new `EmanifestSearch` class we use for querying the e-Manifest API for manifests (the manifest search endpoint). The e-Manifest team kind of uses this search endpoint as a swiss army blade for finding manifest data.
=> EmanifestSearch class

docs/guide/src/development/local-development.md
Edited shell command for installing requirements_dev.txt to point to its location within the server directory
=> requirements_dev.txt location

client/package-lock.json, client/package.json, client/src/components/Manifest/Transporter/TransporterRowActions.tsx, client/src/components/Manifest/Transporter/TransporterSection.tsx, client/src/components/Manifest/Transporter/TransporterTable.spec.tsx, client/src/components/Manifest/Transporter/TransporterTable.tsx, client/src/components/Manifest/manifestSchema.ts, client/src/setupTests.ts
Created a unique key for each Transporter by combining the EPAID and array index. This allows the user to apply all actions in the transporter drop-down menu without side-effects.
I found a bug where the tool-tips in the Transporter list displayed the zero-index value, i.e. 'view transporter 0 details' for transporter 1. I corrected the tests to reflect this change in tool-tip labels since the selectors are based on the index value. 
Added a test to ensure that only one accordion expands when the same Transporter appears in the manifest and 'Details' is clicked.
Closes issue #620 [https://github.com/USEPA/haztrak/issues/620]
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I …
=> Add unique key to transporter array elements 

client/src/components/Manifest/Transporter/TransporterSection.tsx
[PR718](https://github.com/USEPA/haztrak/pull/718) created a break in the Manifest form that prevented the user from adding transporters to the manifest. This PR will change the methodology by which the uuid is added to each transporter in the transporter list.
- [X ] My changes generate no new warnings
=> Repair TransporterSection by properly adding uuid to clientKey

client/src/components/Manifest/GeneralInfo/ManifestStatusSelect.spec.tsx, client/src/components/Manifest/Handler/Search/HandlerSearchForm.spec.tsx, client/src/components/Rcrainfo/buttons/SyncManifestBtn/SyncManifestBtn.spec.tsx, client/src/features/NewManifest/NewManifest.spec.tsx, client/src/hooks/useUserSiteIds/useUserSiteIds.spec.tsx, client/src/store/htApi.slice.ts, client/src/store/userSlice/user.slice.ts, client/src/test-utils/mock/mockManifestEndpoints.ts, client/src/test-utils/mock/mockUserEndpoints.ts, client/src/test-utils/mock/mockWasteEndpoints.ts, server/apps/core/exceptions.py, server/apps/core/tests/test_views.py, server/apps/core/urls.py, server/apps/core/views.py, server/apps/manifest/tests/test_views.py, server/apps/manifest/urls.py, server/apps/manifest/views.py, server/apps/org/tests/test_views.py, server/apps/org/urls.py, server/apps/profile/tests/test_views.py, server/apps/profile/urls.py, server/apps/profile/views.py, server/apps/rcrasite/tests/test_views.py, server/apps/rcrasite/urls.py, server/apps/site/tests/test_views.py, server/apps/site/urls.py, server/apps/wasteline/tests/test_waste_views.py, server/apps/wasteline/urls.py, server/haztrak/urls.py
utilizes the django [naming URL pattern](https://docs.djangoproject.com/en/5.0/topics/http/urls/#naming-url-patterns) to remove hard coded URLs in our test suite.  We also make some modifications to our REST API hierarchy and reosource names.
=> Use django URL names in test suite

docs/guide/src/SUMMARY.md, docs/guide/src/design/auth.md
I have spent the last couple of weeks conducting research, deep diving on the django authenticaion system, and  mocking prototypes to determines our path forward on #735. 
This PR updates our documentaion to reflect my researches findings.
=> Authorization Documentation Updates

client/src/App.scss, client/src/components/Charts/ManifestStatusPieChart/ManifestStatusPieChart.tsx
Visual and interactivity enhancement to the pie chart which can present additional information to the user and indicate the presence click events.
Opened to address issue (https://github.com/USEPA/haztrak/issues/733)
The <Pie> element fires its onAnimationEnd event immediately upon rendering when React strict mode is on. The initial chart animation only works properly when strict mode is turned off. I'm looking for some assistance in solving this problem which doesn't require strict mode to be turned off to see the initial animation in development.
=> Chart enhancement

server/fixtures/dev_data.yaml
title says it all. Quick fix that removes a fixture that points to a model that no longer exists.
=> remove org access fixture

client/src/components/Manifest/SiteSelect/SiteSelect.tsx, client/src/features/NewManifest/NewManifest.spec.tsx
Quick fix for retrieving a user's sites that they can manifest as.
=> fix site select

client/src/components/Charts/ManifestCountBarChart/ManifestCountBarChart.tsx, client/src/components/Charts/ManifestStatusPieChart/ManifestStatusPieChart.tsx, client/src/components/Layout/PrivateRoute.tsx, client/src/components/Layout/Root.tsx, client/src/components/Manifest/Handler/Search/RcrainfoSiteSearchBadge.tsx, client/src/components/Manifest/SiteSelect/SiteTypeSelect.spec.tsx, client/src/components/Manifest/Transporter/TransporterTable.tsx, client/src/components/Manifest/WasteLine/HazardousWasteForm/HazardousWasteForm.tsx, client/src/components/Manifest/WasteLine/HazardousWasteForm/StateWasteCodeSelect.tsx, client/src/components/Manifest/WasteLine/WasteLineTable/WasteLineTable.tsx, client/src/components/UI/FloatingActionBtn.tsx, client/src/components/UI/HtPaginate/HtPaginate.tsx, client/src/features/NewManifest/NewManifest.tsx, client/src/hooks/manifest/useSaveManifest/useSaveManifest.tsx
update our typescript-eslint configs regarding the usage of explicit `any`s.
=> update ts-eslint explicit `any` usage

server/org/fixtures/org_permissions.yaml, server/org/services.py, server/org/tests/test_views.py, server/org/urls.py, server/org/views.py
Adds a list api view for organizations and a fixture for local development that automatically adds view level permissions for the testuser and test organization.
=> Org list view

client/app/features/profile/components/AvatarForm.tsx, client/app/store/htApi.slice.ts, client/app/store/index.ts, client/app/store/userApi/userApi.ts
implments our call to update the users avatar through an RTK query endpoint which automates the process of invalidating the user profile cache and reinitiating request in other components (e.g., the header navigation).
=> Rtk query avatar endpoint
