USEPA/haztrak

docs/Configuration.md
frontend/.env.example
frontend/src/app/store.js
frontend/src/app/user.slice.js
frontend/src/components/About.jsx
frontend/src/components/HtCard/HtCard.js
frontend/src/components/PrivateRoute.jsx
frontend/src/components/Sidebar.jsx
frontend/src/components/TopNav.jsx
frontend/src/features/SiteDetails/SiteDetails.jsx
frontend/src/features/Sites/Sites.js
frontend/src/features/home/Home.jsx
frontend/src/features/login/Login.jsx
frontend/src/features/profile/Profile.jsx
frontend/src/utils/history.js
frontend/src/utils/test-wrapper.jsx

quick fix for user.slice.js logout reducer function logic, docstrings for react components

quick fix and documentation

---

server/requirements_dev.txt

This reverts commit fd5e6a8fad78596bdc938a77253d96a991b9dda3.

Revert "Bump virtualenv from 20.14.1 to 20.16.3 in /server (#76)"

---

.github/workflows/test_server.yml
.gitignore
client/.env.example
client/src/features/help/About.tsx
client/src/services/api.ts
client/src/utils/utils.ts
docker-compose.yaml
docs/Configuration.md
server/.env.example
server/haztrak/settings.py

This PR adds the ability to build and deploy the entire application via docker compose. it currently has the postgres and redis instances commented out, it runs with db.sqlite3 in the docker instance which can be modified and reset on restart every time which is perfect for easy development.

docker-compose config

---

client/src/app/user.slice.ts

PR for issue #134 
Now if the request is failed then the proper error message will be shown.

[Fix] error message in auth state

---

.idea/runConfigurations/celery.xml
client/src/features/login/Login.tsx
client/src/types/Transporter/Transporter.ts

@dpgraham4401 , Please review the changes.

Add interface for transporter.

---

client/src/components/HtCard/HtCard.tsx
client/src/components/ManifestForm/ManifestForm/ManifestForm.tsx

This PR adds a modal component and button in the new manifest page that will house the transporter search form.

modal for transporter search Form

---

client/src/components/ManifestForm/ManifestForm/ManifestForm.tsx
client/src/components/ManifestForm/Tsdf/Tsdf.tsx
client/src/components/ManifestForm/Tsdf/index.ts

This PR adds placeholder UI elements for the Tsdf portion of the ManifestForm
closes #200

ManifestForm Tsdf UI placeholder

---

.github/workflows/mdbook.yaml
docs/haztrak_book/src/Overview/index.md

quick fixes to mdbook workflow

adjust run criteria (again)

---

docs/haztrak_book/src/SUMMARY.md
docs/haztrak_book/src/Setup/contributing.md

Test GH Pages workflow

---

.github/workflows/mdbook.yaml

remove path filter

---

.github/workflows/mdbook.yaml

remove marketpalce actions from doc generator

---

client/Dockerfile
docker-compose.yaml

upgraded node in dockerfile
issue link: https://github.com/USEPA/haztrak/issues/285
#285
closes #285

feat: bump node from 16 to 18

---

docs/haztrak_book/src/SUMMARY.md
docs/haztrak_book/src/deploy/testing.md
docs/haztrak_book/src/design/back-end-errors.md
docs/haztrak_book/src/design/index.md
docs/haztrak_book/src/design/sdd.md
docs/haztrak_book/src/design/testing.md
server/apps/trak/tests/conftest.py
server/apps/trak/tests/views/test_handler_api.py
server/haztrak/settings.py

This PR updates our documentation, namely our sections on...
- CI
- CD
- testing
- scope
- scaffolding a placeholder for back end error design
closes #356 
closes #265
closes #264 
adds a placeholder markdown doc for # 304

Doc updates

---

server/apps/trak/models/handler_model.py
server/apps/trak/models/signature_model.py
server/apps/trak/serializers/handler_ser.py
server/apps/trak/serializers/signature_ser.py
server/apps/trak/tests/conftest.py
server/apps/trak/tests/resources/json/paper_manifest_handler.json
server/apps/trak/tests/serializers/test_handler_serializer.py

This PR adds the `PaperSignatureSerializer` class and incorperates it into the current `ManifestHandlerSerializer` and it's corresponding methods
close #375

375 papersignaturesinfo serializer

---

client/src/features/site/SiteDetails/SiteDetails.tsx

Proposed for Issue View Site Manifest Button #379

---

server/apps/trak/tests/conftest.py
server/apps/trak/tests/models/test_address.py
server/apps/trak/tests/models/test_handler.py
server/apps/trak/tests/models/test_profile.py
server/apps/trak/tests/models/test_signatures.py
server/apps/trak/tests/serializers/test_handler_serializer.py
server/apps/trak/tests/serializers/test_permissions_serializer.py
server/apps/trak/tests/serializers/test_signature_serializer.py
server/apps/trak/tests/services/test_handler_services.py
server/apps/trak/tests/services/test_manifest_services.py
server/apps/trak/tests/services/test_rcrainfo_services.py
server/apps/trak/tests/services/test_site_services.py
server/apps/trak/tests/views/test_handler_api.py
server/apps/trak/tests/views/test_handler_search_api.py
server/apps/trak/tests/views/test_manifest_viewset.py
server/apps/trak/tests/views/test_rcra_profile.py
server/apps/trak/tests/views/test_site_api.py

This PR refactors our server test suite as discussed in #391 by implementing abstract factory as our test suite fixtures.
closes #391

391 factory fixtures

---

server/requirements.txt

upgraded psycopg-binary

---

client/package-lock.json
client/package.json
client/src/components/Mtn/MtnRowActions.tsx
client/src/components/Mtn/MtnTable.spec.tsx
client/src/components/Mtn/MtnTable.tsx
client/src/features/manifest/Manifest.tsx
client/src/features/manifest/ManifestList.tsx

This PR adds react-table (v8) into our client side dependencies and uses it in the existing `MtnTable` component. With it we get pagination, searching/filtering, and sorting basically out of the box. This PR adds a global search to the MtnTable component so manifest can be filtered by MTN with this PR however I would like to expand on this. 
relevant to #415 #401

React-table-v8

---

.github/workflows/dependency_review.yaml

closes #353 
This is currently a work-in-progress, hence I'm opening it as a draft PR. I've left a few questions on the issue (referenced above) that I think you'll want to nail down before calling this one done. Happy to work with you and make any changes needed here.

First cut workflow for dependency check

---

.github/workflows/dependency_review.yaml
client/package-lock.json
server/requirements.txt

This PR updates our emanifestpy version to the 3.0.5 patch, mostly just for fun to test out our new dependency review workflow #353

update to emanifest 3.0.5

---

client/src/features/profile/Profile.tsx

remove 2nd container in profile feature to fix the vertical alignment in the page.

Fix profile alignment

---

.github/release-drafter.yml

I made a POC project, this should fix the auto labeler. It worked there, I'm going to be upset if it doesn't work here.

fix auto-labeler

---

.github/workflows/test_server.yaml
configs/.env.test
runhaz.sh
server/haztrak/settings.py

This reverts commit f30a988c5806f2ae2fc43f19f6b6fe5f62496f3b.
We had some unexpected changes when updating our dependencies. This PR revert our main branch to the commit that preceded the  PR #536 
we started receiving an error similar to this in our ManifestForm 
[React maximum update depth exceeded | useEffect dependencies](https://stackoverflow.com/questions/69292568/react-maximum-update-depth-exceeded-useeffect-dependencies)
We'll chalk this one up to being busy and a lesson learned. **update dependencies with care** especially out client side dependencies (the javascript community likes to breaks stuff and move quickly).

Revert "Use postgres in workflow (#534)"

---

client/src/components/Manifest/ManifestForm.tsx
client/src/components/Manifest/WasteLine/EditWasteModal.tsx
client/src/components/Manifest/WasteLine/WasteLineForm.spec.tsx
client/src/components/Manifest/WasteLine/WasteLineForm.tsx
client/src/components/Manifest/WasteLine/WasteLineTable/WasteLineTable.tsx
client/src/components/Manifest/WasteLine/WasteLineTable/WasteRowActions.tsx
client/src/components/Manifest/WasteLine/index.ts

This PR adds the ability to delete and edit waste lines. nuf said. 
closes #564

Wastelines Row Actions

---

client/package-lock.json
client/package.json
server/requirements.txt
server/requirements_dev.txt

update our dependencies per dependabot PRs.

Dependabot updates

---

.devcontainer/.env.devcontainer
.devcontainer/Trak/Dockerfile
.devcontainer/Trak/devcontainer.json
.devcontainer/docker-compose.yml
.github/dependabot.yml
client/package-lock.json
docker-compose.yaml

Initial .devcontainers configuration. This feature is still incomplete and has is not documented yet. This config allows people to develop locally with docker in a familiar way for those familiar with the dev container environment, as well as those without docker on their local machine can use github codespaces to make changes online.

Dev Container configuration

---

.github/workflows/codeql.yml
server/fixtures/dev_data.yaml
server/requirements.txt

some quick patches for dependencies and fix for our development fixtures

Dep patches

---

client/package-lock.json
client/package.json
server/requirements_dev.txt

Dep review

---

client/src/components/Layout/TopNav/TopNav.tsx
client/src/store/index.ts
client/src/store/userSlice/user.slice.ts

fix to client side mutation for the logout endpoint.

client logout mutation

---

client/app/features/layout/Root.tsx
client/app/features/siteDetails/SiteDetails.tsx
client/app/services/APIs/htApi.spec.tsx
client/app/services/APIs/htApi.ts
client/package.json
server/pyproject.toml

Some quick fixes to our client side http client to handle when user makes unauthenticated request and automatically redirect suers to the login page. 
also increment versino 0.8.0

Client auth fixes

---

client/app/components/Manifest/Actions/ManifestCancelBtn.tsx
client/app/components/Manifest/Actions/ManifestEditBtn.tsx
client/app/components/Manifest/Actions/ManifestSaveBtn.tsx
client/app/components/RcraSite/RcraSiteDetails.tsx
client/app/components/Rcrainfo/buttons/SyncManifestBtn/SyncManifestBtn.tsx
client/app/components/User/UserInfoForm.tsx
client/app/components/legacyUi/HtPaginate/HtPageBtns.tsx
client/app/components/legacyUi/HtTooltip/HtTooltip.tsx
client/app/components/ui/Avatar/Avatar.spec.tsx
client/app/components/ui/Avatar/Avatar.tsx
client/app/components/ui/Button/Button.tsx
client/app/components/ui/index.ts
client/package-lock.json
client/package.json
server/manifest/serializers/handler_serializer.py
server/manifest/serializers/manifest.py
server/manifest/serializers/mixins.py
server/manifest/serializers/signatures.py
server/manifest/urls.py
server/manifest/views.py
server/profile/views.py

Cosmetic fixes for front end icons and a new avatar component. this PR also makes a fix to our manifest app url routing.

Icon cosmetic fixes and avatar component

---

server/requirements_dev.txt

update ruff deps

---

.github/workflows/lint_client.yaml
.github/workflows/test_client.yaml
client/.prettierrc.json

add end of line = auto prettier config for working on windows and add Node version 22 in our CI (drop support for Node 18).

Support Node 22

---

server/requirements.txt

update djangorestframework-simplejwt version

---

compose.yaml
server/Dockerfile
server/run.sh

Get baseline local devlopment docker back up and running after migrating to uv

Docker uv migration
